# Generated by Django 6.0.8 on 2026-09-24 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_userworkspacestate'),
        ('knowledge', '0003_ruleversion_rule_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workflows_application_form',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(default='REGULATORY', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'workflows_definition',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requirement_id_code', models.CharField(db_index=True, max_length=100)),
                ('status_code', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('ACTION_REQUIRED', 'Action required'), ('HUMAN_REVIEW', 'Human review'), ('SUBMITTED', 'Submitted'), ('EXTERNAL_PROCESSING', 'External processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases', to='businesses.assessment')),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance_cases', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_cases', to='businesses.business')),
                ('profile_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases', to='businesses.businessprofileversion')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_cases', to='knowledge.requirementdefinition')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases', to='knowledge.ruleversion')),
                ('workflow_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflows_compliance_case',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalApplicationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_name', models.CharField(max_length=100)),
                ('application_reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('status_code', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('QUERY_RAISED', 'Query raised'), ('RESUBMISSION_REQUIRED', 'Resubmission required'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('UNKNOWN', 'Unknown')], default='SUBMITTED', max_length=50)),
                ('status_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('portal_remarks', models.TextField(blank=True, default='')),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('compliance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_statuses', to='workflows.compliancecase')),
            ],
            options={
                'db_table': 'workflows_external_application_status',
                'ordering': ['-status_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('compliance_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.compliancecase')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_notification_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinitionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='PUBLISHED', max_length=30)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflows_definition_version',
                'ordering': ['workflow_definition', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowdefinitionversion'),
        ),
        migrations.AddField(
            model_name='compliancecase',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases', to='workflows.workflowdefinitionversion'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_USER', 'Waiting for you'), ('UNDER_REVIEW', 'Under review'), ('NEEDS_CORRECTION', 'Needs correction'), ('READY', 'Ready'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('BLOCKED', 'Blocked')], default='IN_PROGRESS', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('compliance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='workflows.compliancecase')),
                ('workflow_definition_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowdefinitionversion')),
            ],
            options={
                'db_table': 'workflows_instance',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='compliancecase',
            name='current_workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowinstance'),
        ),
        migrations.CreateModel(
            name='WorkflowStepDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('INFORMATION', 'Information'), ('DOCUMENT_COLLECTION', 'Document collection'), ('DOCUMENT_REVIEW', 'Document review'), ('HUMAN_REVIEW', 'Human review'), ('FORM_PREPARATION', 'Form preparation'), ('FORM_REVIEW', 'Form review'), ('USER_SUBMISSION', 'User submission'), ('EXTERNAL_PROCESSING', 'External processing'), ('QUERY_RESOLUTION', 'Query resolution'), ('APPROVAL', 'Approval'), ('REJECTION', 'Rejection'), ('COMPLETION', 'Completion')], default='INFORMATION', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_definitions', to='workflows.workflowdefinitionversion')),
            ],
            options={
                'db_table': 'workflows_step_definition',
                'ordering': ['workflow_version', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstepdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_code', models.CharField(db_index=True, max_length=100)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('EXTERNAL', 'External'), ('ANY', 'Any')], default='SYSTEM', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('compliance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflows.compliancecase')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflows.workflowinstance')),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstepdefinition')),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstepdefinition')),
            ],
            options={
                'db_table': 'workflows_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_INPUT', 'Waiting for input'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('BLOCKED', 'Blocked')], default='NOT_STARTED', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_role', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('step_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workflows.workflowstepdefinition')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='workflows.workflowinstance')),
            ],
            options={
                'db_table': 'workflows_step_instance',
                'ordering': ['workflow_instance', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('status_code', models.CharField(default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('compliance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='workflows.compliancecase')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workflows.applicationform')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow_step_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='workflows.workflowstepinstance')),
            ],
            options={
                'db_table': 'workflows_form_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(db_index=True, max_length=100)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('allowed_actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('EXTERNAL', 'External'), ('ANY', 'Any')], default='ANY', max_length=30)),
                ('priority', models.IntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstepdefinition')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstepdefinition')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_definitions', to='workflows.workflowdefinitionversion')),
            ],
            options={
                'db_table': 'workflows_transition_definition',
                'ordering': ['priority', 'event_code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('PUSH', 'Push'), ('GOOGLE_CALENDAR', 'Google calendar')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('notification_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='workflows.notificationevent')),
            ],
            options={
                'db_table': 'workflows_notification_delivery',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('notification_event', 'channel'), name='uniq_delivery_event_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowdefinitionversion',
            constraint=models.UniqueConstraint(fields=('workflow_definition', 'version_number'), name='uniq_workflow_version'),
        ),
        migrations.AddIndex(
            model_name='compliancecase',
            index=models.Index(fields=['business', 'status_code'], name='workflows_c_busines_e8bf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecase',
            index=models.Index(fields=['requirement_id_code', 'status_code'], name='workflows_c_require_d7d94c_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstepdefinition',
            constraint=models.UniqueConstraint(fields=('workflow_version', 'code'), name='uniq_step_code_per_version'),
        ),
    ]
