# Generated by Django 6.0.8 on 2026-09-25 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentreview_status_and_more'),
        ('knowledge', '0003_ruleversion_rule_type_and_more'),
        ('workflows', '0002_reviewtask_humanreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecase',
            name='concurrency_version',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Optimistic concurrency control version. Increments on every transition/action.'),
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflows_outbox_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='workflows_o_status_2d4200_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('EXTERNAL', 'External'), ('ANY', 'Any')], default='USER', max_length=30)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_security_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_type', models.CharField(choices=[('DOCUMENT_CORRECTION', 'Document correction'), ('INFORMATION_REQUEST', 'Information request'), ('SCOPE_CLARIFICATION', 'Scope clarification'), ('RENEWAL_REMINDER', 'Renewal reminder')], default='DOCUMENT_CORRECTION', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('required_action', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDED', 'Responded'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_queries', to='workflows.compliancecase')),
                ('document_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_queries', to='documents.documentrequirement')),
                ('document_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_queries', to='documents.documentsubmission')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_case_queries', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_case_query',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='workflows_c_case_id_76f644_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseRequirementDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id_code', models.CharField(db_index=True, max_length=100)),
                ('original_applicability_status', models.CharField(default='APPLICABLE', help_text='Immutable rule-engine result (APPLICABLE, CONDITIONAL, etc.)', max_length=50)),
                ('admin_disposition', models.CharField(choices=[('SYSTEM_REVIEW_PENDING', 'System review pending'), ('CONFIRMED_REQUIRED', 'Confirmed required'), ('NOT_REQUIRED', 'Not required'), ('NEEDS_INFORMATION', 'Needs information'), ('REQUEST_USER_INFORMATION', 'Request user information'), ('ADMIN_ASSIGNED', 'Admin assigned'), ('ESCALATED', 'Escalated')], db_index=True, default='CONFIRMED_REQUIRED', max_length=50)),
                ('source', models.CharField(default='SYSTEM_RULE', help_text='SYSTEM_RULE, ADMIN_ASSIGNED, or CATALOG_ATTACHED', max_length=50)),
                ('reason', models.TextField(blank=True, default='', help_text='Mandatory rationale when changing treatment from default rule evaluation')),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('user_visible', models.BooleanField(default=True)),
                ('user_action_required', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='workflows.compliancecase')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_dispositions', to='knowledge.requirementdefinition')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_dispositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_requirement_disposition',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('case', 'requirement_id_code'), name='uniq_case_requirement_disposition')],
            },
        ),
    ]
