# Generated by Django 6.0.8 on 2026-09-05 13:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_runs', to='businesses.business')),
                ('profile_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_runs', to='businesses.businessprofileversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(db_index=True, max_length=100)),
                ('requirement_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('APPLICABLE', 'Applicable'), ('NOT_APPLICABLE', 'Not applicable'), ('NEEDS_INFORMATION', 'More information needed'), ('CONFLICT_REVIEW', 'Review required'), ('UNVERIFIED', 'Verification required')], db_index=True, default='UNVERIFIED', max_length=30)),
                ('explanation_trace', models.JSONField(default=dict, help_text='Detailed trace: rule ID, conditions evaluated, variables used, values, and result.')),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='Evidence records backing this determination.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_results', to='knowledge.ruleversion')),
                ('decision_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='applicability.decisionrun')),
            ],
            options={
                'ordering': ['requirement_id'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionrun',
            index=models.Index(fields=['business', 'created_at'], name='applicabili_busines_2190ef_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionresult',
            index=models.Index(fields=['decision_run', 'status'], name='applicabili_decisio_0ca43c_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionresult',
            index=models.Index(fields=['requirement_id', 'status'], name='applicabili_require_111bba_idx'),
        ),
    ]
