# Generated by Django 6.0.8 on 2026-09-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicability', '0002_alter_decisionrun_evaluation_date'),
        ('businesses', '0002_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionrun',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_run_records', to='businesses.assessment'),
        ),
    ]
