# Generated by Django 6.0.8 on 2026-09-22 14:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('authority', models.CharField(db_index=True, max_length=200)),
                ('jurisdiction', models.CharField(db_index=True, default='CENTRAL', help_text='CENTRAL, MH (Maharashtra), etc.', max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('source_domain', models.CharField(db_index=True, max_length=150)),
                ('current_version_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['jurisdiction', 'title'],
                'indexes': [models.Index(fields=['jurisdiction', 'is_active'], name='schemes_sch_jurisdi_58b0a4_idx'), models.Index(fields=['authority', 'is_active'], name='schemes_sch_authori_50b313_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemeRollbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_version', models.PositiveIntegerField()),
                ('to_version', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('reverted_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_logs', to='schemes.scheme')),
            ],
            options={
                'ordering': ['-reverted_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeSourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(db_index=True, help_text='CENTRAL_MSME, MSME_CHAMPIONS, DPIIT_OFFERINGS, MAHARASHTRA_MCED, MAITRI_PORTAL', max_length=60)),
                ('source_url', models.URLField(max_length=500)),
                ('source_domain', models.CharField(max_length=150)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of the raw snapshot payload.', max_length=64)),
                ('status', models.CharField(default='SUCCESS', help_text='SUCCESS, UNCHANGED, FAILED', max_length=30)),
                ('scheme_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source_key', '-fetched_at'], name='schemes_sch_source__8f82f4_idx'), models.Index(fields=['content_hash'], name='schemes_sch_content_642904_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(db_index=True)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 fingerprint of the normalized scheme metadata.', max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('authority', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(default='CENTRAL', max_length=50)),
                ('summary', models.TextField()),
                ('benefit_type', models.CharField(default='INCENTIVE_SCHEME', help_text='CAPITAL_SUBSIDY, INTEREST_SUBVENTION, CREDIT_GUARANTEE, DUTY_REMISSION, TAX_EXEMPTION, QUALITY_CERTIFICATION, etc.', max_length=60)),
                ('benefit_summary', models.TextField()),
                ('benefit_details', models.JSONField(blank=True, default=dict, help_text='Structured quantitative terms: subsidy_rate, ceiling_amount, moratorium, etc.')),
                ('eligibility_statement', models.TextField()),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict, help_text='Machine-evaluable criteria: min_investment, max_investment, turnover_cap, activities, required_certifications.')),
                ('sectors', models.JSONField(blank=True, default=list, help_text="List of targeted sectors, e.g. ['MANUFACTURING', 'TEXTILE', 'FOOD_PROCESSING', 'ALL'].")),
                ('scale_match', models.JSONField(blank=True, default=list, help_text="List of eligible MSME scales, e.g. ['MICRO', 'SMALL', 'MEDIUM'].")),
                ('application_route', models.TextField(blank=True, default='')),
                ('application_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_url', models.URLField(max_length=500)),
                ('source_domain', models.CharField(blank=True, default='', max_length=150)),
                ('evidence_snippet', models.TextField(blank=True, default='', help_text='Verbatim quote or clause from official publication citing source fact.')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(db_index=True, default='VERIFIED', help_text='VERIFIED, PENDING_REVIEW, ARCHIVED', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('diff_summary', models.JSONField(blank=True, default=dict, help_text='Diff details comparing this version against version_number - 1.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schemes.scheme')),
            ],
            options={
                'ordering': ['scheme', '-version_number'],
                'indexes': [models.Index(fields=['scheme', 'is_active'], name='schemes_sch_scheme__653343_idx'), models.Index(fields=['jurisdiction', 'verification_status'], name='schemes_sch_jurisdi_bc7e0c_idx'), models.Index(fields=['content_hash'], name='schemes_sch_content_c875a2_idx')],
                'unique_together': {('scheme', 'version_number')},
            },
        ),
    ]
