# Generated by Django 6.0.8 on 2026-09-12 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineNotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id', models.CharField(db_index=True, max_length=255)),
                ('deadline_date', models.DateField(db_index=True)),
                ('offset_days', models.PositiveIntegerField(help_text='Days remaining at time of dispatch (7 for T-7, 1 for T-1)')),
                ('channel', models.CharField(choices=[('GOOGLE_CALENDAR', 'Google Calendar'), ('EMAIL', 'Email')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('SIMULATED', 'Simulated'), ('SKIPPED_DUPLICATE', 'Skipped (Duplicate)'), ('FAILED', 'Failed')], default='DELIVERED', max_length=32)),
                ('language', models.CharField(default='en', help_text='Language code: en, hi, bn', max_length=10)),
                ('subject_or_title', models.CharField(blank=True, default='', max_length=500)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_deadline_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'deadline_date'], name='calendar_de_busines_5b050b_idx'), models.Index(fields=['user', '-created_at'], name='calendar_de_user_id_ef7e04_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'business', 'requirement_id', 'deadline_date', 'offset_days', 'channel'), name='uniq_calendar_deadline_notification')],
            },
        ),
    ]
