# Generated by Django 6.0.8 on 2026-09-13 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_userworkspacestate'),
        ('calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('calendar_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', help_text='Language code: en, hi, bn', max_length=10)),
            ],
            options={
                'db_table': 'calendar_notification_preference',
            },
        ),
        migrations.RemoveConstraint(
            model_name='deadlinenotificationdelivery',
            name='uniq_calendar_deadline_notification',
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='event_type',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OVERDUE', 'Overdue'), ('ESCALATION', 'Escalation')], db_index=True, default='UPCOMING', max_length=32),
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=16),
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deadlinenotificationdelivery',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadlinenotificationdelivery',
            name='channel',
            field=models.CharField(choices=[('GOOGLE_CALENDAR', 'Google Calendar'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='deadlinenotificationdelivery',
            name='offset_days',
            field=models.PositiveIntegerField(help_text='Days remaining (upcoming) or days overdue (overdue) at time of dispatch'),
        ),
        migrations.AlterField(
            model_name='deadlinenotificationdelivery',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('SIMULATED', 'Simulated'), ('SKIPPED_DUPLICATE', 'Skipped (Duplicate)'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('RETRYING', 'Retrying')], default='DELIVERED', max_length=32),
        ),
        migrations.AddIndex(
            model_name='deadlinenotificationdelivery',
            index=models.Index(fields=['business', 'is_read'], name='calendar_de_busines_49381f_idx'),
        ),
        migrations.AddIndex(
            model_name='deadlinenotificationdelivery',
            index=models.Index(fields=['event_type', 'status'], name='calendar_de_event_t_0d94bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='deadlinenotificationdelivery',
            constraint=models.UniqueConstraint(fields=('user', 'business', 'requirement_id', 'deadline_date', 'offset_days', 'channel', 'event_type'), name='uniq_calendar_deadline_notification_v2'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'business'), name='uniq_user_business_notification_preference'),
        ),
    ]
