# Generated by Django 6.0.8 on 2026-09-25 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_userworkspacestate'),
        ('calendar', '0003_usergooglecalendarconnection'),
        ('knowledge', '0003_ruleversion_rule_type_and_more'),
        ('workflows', '0002_reviewtask_humanreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id_code', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('SYSTEM_RULE', 'System rule'), ('ADMIN_SET', 'Admin set'), ('EXTERNAL_PORTAL', 'External portal'), ('RENEWAL', 'Renewal')], db_index=True, default='ADMIN_SET', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('reminder_policy', models.JSONField(blank=True, default=dict, help_text="Configured alert triggers (e.g. {'days_before': [7, 3, 1]})")),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID for idempotent synchronization', max_length=255, null=True)),
                ('email_notification_enabled', models.BooleanField(default=True)),
                ('calendar_notification_enabled', models.BooleanField(default=True)),
                ('in_app_notification_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_deadlines', to='businesses.business')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_deadlines', to='workflows.compliancecase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_deadlines', to='knowledge.requirementdefinition')),
            ],
            options={
                'db_table': 'calendar_deadline',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['business', 'due_at'], name='calendar_de_busines_266b2a_idx'), models.Index(fields=['case', 'status'], name='calendar_de_case_id_aac195_idx')],
            },
        ),
    ]
