# Generated by Django 6.0.8 on 2026-09-05 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='LICENCE', help_text='LICENCE, REGISTRATION, CONSENT, COMPLIANCE, STANDARD, APPROVAL, etc.', max_length=50)),
                ('authority', models.CharField(db_index=True, max_length=100)),
                ('jurisdiction', models.CharField(db_index=True, help_text='CENTRAL, GUJARAT, TELANGANA, TAMIL_NADU, KARNATAKA, etc.', max_length=50)),
                ('domain', models.CharField(db_index=True, help_text='FOOD, ELECTRONICS, ENVIRONMENT, TRADE, AUTOMOTIVE, LABOR, etc.', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATION_PENDING', 'Validation pending'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='List of evidence_id strings supporting this requirement.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['authority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('domain', models.CharField(db_index=True, max_length=50)),
                ('jurisdiction', models.CharField(db_index=True, max_length=50)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATION_PENDING', 'Validation pending'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('condition_ast', models.JSONField(help_text='Structured condition AST evaluated by domain.evaluation.evaluator.')),
                ('result', models.CharField(default='APPLICABLE', help_text='Outcome when condition AST evaluates to TRUE.', max_length=50)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='List of evidence_id strings supporting this rule version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='knowledge.requirementdefinition')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='knowledge.ruleversion')),
            ],
            options={
                'ordering': ['rule_id', '-version'],
                'indexes': [models.Index(fields=['status', 'effective_from', 'effective_until'], name='knowledge_r_status_753389_idx'), models.Index(fields=['jurisdiction', 'domain', 'status'], name='knowledge_r_jurisdi_c8b30f_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule_id', 'version'), name='unique_rule_version')],
            },
        ),
    ]
