# Generated by Django 6.0.8 on 2026-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleversion',
            name='rule_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EXCEPTION', 'Exception'), ('OVERRIDE', 'Override'), ('EXEMPTION', 'Exemption')], db_index=True, default='NORMAL', help_text='Precedence level: OVERRIDE > EXEMPTION > EXCEPTION > NORMAL.', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirementdefinition',
            name='jurisdiction',
            field=models.CharField(db_index=True, help_text='Jurisdiction code (e.g. CENTRAL or state/union territory code).', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruleversion',
            name='result',
            field=models.CharField(choices=[('APPLICABLE', 'Applicable'), ('NOT_APPLICABLE', 'Not applicable'), ('NEEDS_INFORMATION', 'More information needed'), ('CONFLICT_REVIEW', 'Review required'), ('UNVERIFIED', 'Verification required')], default='APPLICABLE', help_text='Outcome when condition AST evaluates to TRUE.', max_length=50),
        ),
    ]
