# Generated by Django 6.0.8 on 2026-09-05 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('authority', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(default='REGULATION', help_text='ACT, REGULATION, NOTIFICATION, OFFICIAL_PORTAL, CIRCULAR, etc.', max_length=50)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UPDATED', 'Updated'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn'), ('CONFLICTING', 'Conflicting')], db_index=True, default='ACTIVE', max_length=30)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['authority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('locator', models.CharField(blank=True, default='', help_text='Section, Schedule, Clause or Page locator in the source document.', max_length=200)),
                ('excerpt', models.TextField(help_text='Verbatim quote or structured extract from source.')),
                ('structured_fact', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('CONFLICTING', 'Conflicting')], db_index=True, default='UNVERIFIED', max_length=30)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='evidence.source')),
            ],
            options={
                'ordering': ['evidence_id'],
                'indexes': [models.Index(fields=['source', 'verification_status'], name='evidence_ev_source__b04bfa_idx')],
            },
        ),
    ]
