# Generated by Django 6.0.8 on 2026-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UPDATED', 'Updated'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn'), ('CONFLICTING', 'Conflicting'), ('DISCOVERED', 'Discovered (unverified)')], db_index=True, default='ACTIVE', max_length=30),
        ),
    ]
