# Generated by Django 6.0.8 on 2026-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPLIANCE_OFFICER', 'Compliance Officer'), ('SENIOR_OFFICER', 'Senior Officer'), ('AUDITOR', 'Auditor'), ('SUPER_ADMIN', 'Super Admin'), ('USER', 'User')], default='USER', help_text='Operational role (COMPLIANCE_OFFICER, SENIOR_OFFICER, AUDITOR, SUPER_ADMIN, USER)', max_length=50),
        ),
    ]
