# Generated by Django 6.0.8 on 2026-10-03 18:29

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleLoginAttempt',
            fields=[
                ('state_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=128)),
                ('code_verifier', models.CharField(max_length=128)),
                ('handoff_challenge', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('callback_used_at', models.DateTimeField(null=True)),
                ('ticket_digest', models.CharField(max_length=64, null=True, unique=True)),
                ('ticket_used_at', models.DateTimeField(null=True)),
                ('is_new_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email_casefold'),
        ),
        migrations.AddField(
            model_name='googleidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googleloginattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
