import type { ProfileVariableDefinition } from "@/types";

// Existing offline option contract; live definitions take precedence.
export const FALLBACK_VAR_DEFS: ProfileVariableDefinition[] = [
  {
    code: "def-constitution",
    key: "legal_constitution",
    label: "Legal Constitution",
    data_type: "SINGLE_CHOICE",
    why_it_matters: "Determines corporate filing and statutory board obligations.",
    unit: null,
    default_relevance: "CORE",
    options: [
      { value: "PRIVATE_LIMITED", label: "Private Limited Company (Pvt Ltd)" },
      { value: "PUBLIC_LIMITED", label: "Public Limited Company" },
      { value: "LLP", label: "Limited Liability Partnership (LLP)" },
      { value: "PROPRIETORSHIP", label: "Sole Proprietorship" },
      { value: "PARTNERSHIP", label: "Partnership Firm" },
    ],
  },
  {
    code: "def-state",
    key: "state",
    label: "Registered State / UT",
    data_type: "SINGLE_CHOICE",
    why_it_matters: "Governs State Pollution Control Board and municipal jurisdiction.",
    unit: null,
    default_relevance: "CORE",
    options: [
      { value: "ANDHRA_PRADESH", label: "Andhra Pradesh" },
      { value: "CENTRAL", label: "Central (All India)" },
      { value: "DELHI", label: "Delhi (NCT)" },
      { value: "GUJARAT", label: "Gujarat" },
      { value: "HARYANA", label: "Haryana" },
      { value: "KARNATAKA", label: "Karnataka" },
      { value: "KERALA", label: "Kerala" },
      { value: "MADHYA_PRADESH", label: "Madhya Pradesh" },
      { value: "MAHARASHTRA", label: "Maharashtra" },
      { value: "ODISHA", label: "Odisha" },
      { value: "PUNJAB", label: "Punjab" },
      { value: "RAJASTHAN", label: "Rajasthan" },
      { value: "TAMIL_NADU", label: "Tamil Nadu" },
      { value: "TELANGANA", label: "Telangana" },
      { value: "UTTAR_PRADESH", label: "Uttar Pradesh" },
      { value: "WEST_BENGAL", label: "West Bengal" },
    ],
  },
  {
    code: "def-zone",
    key: "industrial_zone_status",
    label: "Industrial Zone Status",
    data_type: "SINGLE_CHOICE",
    why_it_matters: "Affects siting guidelines and environmental clearance fast-tracks.",
    unit: null,
    default_relevance: "CORE",
    options: [
      { value: "INSIDE_NOTIFIED_INDUSTRIAL_AREA", label: "Approved Industrial Estate (GIDC / HSIIDC / KIADB / MIDC)" },
      { value: "NON_CONFORMING", label: "Non-conforming Industrial Area" },
      { value: "SPECIAL_ECONOMIC_ZONE", label: "Special Economic Zone (SEZ)" },
    ],
  },
  {
    code: "def-stage",
    key: "lifecycle_stage",
    label: "Operational Lifecycle Stage",
    data_type: "SINGLE_CHOICE",
    why_it_matters: "Separates pre-commissioning consent (CTE) from operating license (CTO).",
    unit: null,
    default_relevance: "CORE",
    options: [
      { value: "OPERATIONAL", label: "Fully Operational Manufacturing" },
      { value: "EXPANSION", label: "Operational & Under Expansion" },
      { value: "PRE_COMMISSIONING", label: "Pre-commissioning / Factory Setup" },
    ],
  },
  {
    code: "def-trade",
    key: "import_export_intent",
    label: "Trade Intent",
    data_type: "SINGLE_CHOICE",
    why_it_matters: "Determines requirement for DGFT Import Export Code (IEC).",
    unit: null,
    default_relevance: "CORE",
    options: [
      { value: "DOMESTIC_ONLY", label: "Domestic Market Only" },
      { value: "IMPORT_AND_DOMESTIC", label: "Domestic + Raw Material Imports" },
      { value: "EXPORTER", label: "Domestic + Finished Goods Exporter" },
    ],
  },
];
