# Generated by Django 6.0.8 on 2026-09-24 20:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type_code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=True)),
                ('status_code', models.CharField(choices=[('NOT_UPLOADED', 'Not uploaded'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('ISSUE', 'Issue found'), ('NEEDS_REVIEW', 'Needs review'), ('EXPIRED', 'Expired'), ('REPLACEMENT_REQUIRED', 'Replacement required')], default='NOT_UPLOADED', max_length=50)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'documents_requirement',
                'ordering': ['case', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('AI_PRECHECK', 'AI precheck'), ('HUMAN_REVIEW', 'Human review')], default='AI_PRECHECK', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INTERNAL_HUMAN_APPROVED', 'Internal approved'), ('INTERNAL_HUMAN_QUERY', 'Internal query raised'), ('INTERNAL_HUMAN_REJECTED', 'Internal rejected')], default='PENDING', max_length=50)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('reviewer_comments', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'documents_review',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('status_code', models.CharField(choices=[('PENDING', 'Pending'), ('INTERNAL_HUMAN_APPROVED', 'Internal approved'), ('INTERNAL_HUMAN_QUERY', 'Internal query raised'), ('INTERNAL_HUMAN_REJECTED', 'Internal rejected')], default='PENDING', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'documents_submission',
                'ordering': ['document_requirement', '-version_number'],
            },
        ),
    ]
