# Generated by Django 6.0.8 on 2026-09-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='workflows.compliancecase'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='workflow_step_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requirements', to='workflows.workflowstepinstance'),
        ),
        migrations.AddField(
            model_name='documentreview',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='document_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='documents.documentrequirement'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.documentsubmission'),
        ),
        migrations.AddConstraint(
            model_name='documentsubmission',
            constraint=models.UniqueConstraint(fields=('document_requirement', 'version_number'), name='uniq_doc_submission_version'),
        ),
    ]
