# Generated by Django 6.0.8 on 2026-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRECHECK_QUEUED', 'Precheck queued'), ('PRECHECK_PROCESSING', 'Precheck processing'), ('PRECHECK_PASSED', 'Precheck passed'), ('PRECHECK_FAILED', 'Precheck issues detected'), ('PRECHECK_ERROR', 'Precheck technical error'), ('PRECHECK_RETRYING', 'Precheck retrying'), ('INTERNAL_HUMAN_APPROVED', 'Internal approved'), ('INTERNAL_HUMAN_QUERY', 'Internal query raised'), ('INTERNAL_HUMAN_REJECTED', 'Internal rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='status_code',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRECHECK_QUEUED', 'Precheck queued'), ('PRECHECK_PROCESSING', 'Precheck processing'), ('PRECHECK_PASSED', 'Precheck passed'), ('PRECHECK_FAILED', 'Precheck issues detected'), ('PRECHECK_ERROR', 'Precheck technical error'), ('PRECHECK_RETRYING', 'Precheck retrying'), ('INTERNAL_HUMAN_APPROVED', 'Internal approved'), ('INTERNAL_HUMAN_QUERY', 'Internal query raised'), ('INTERNAL_HUMAN_REJECTED', 'Internal rejected')], default='PENDING', max_length=50),
        ),
    ]
