# Generated by Django 6.0.8 on 2026-09-07 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartQuestionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='ACTIVE', help_text='ACTIVE, COMPLETED, SUPERSEDED', max_length=30)),
                ('stopping_reason', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_plans', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartQuestionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variable_key', models.CharField(db_index=True, help_text='Canonical variable key (V01-V19) in the profile registry.', max_length=100)),
                ('question_text', models.TextField()),
                ('why_it_matters', models.TextField(blank=True, default='')),
                ('data_type', models.CharField(default='TEXT', max_length=30)),
                ('options', models.JSONField(blank=True, default=list)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('priority', models.CharField(default='HIGH', max_length=20)),
                ('information_gain', models.FloatField(default=1.0)),
                ('rule_dependency_count', models.IntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_questions', to='businesses.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onboarding.smartquestionplan')),
            ],
            options={
                'ordering': ['-priority', '-information_gain', 'created_at'],
                'indexes': [models.Index(fields=['business', 'variable_key'], name='onboarding__busines_0b5f17_idx'), models.Index(fields=['plan', 'is_answered'], name='onboarding__plan_id_40cebf_idx')],
            },
        ),
    ]
