# Generated by Django 6.0.8 on 2026-09-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_assessment'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartquestioninstance',
            name='domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smartquestioninstance',
            name='question_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='smartquestioninstance',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smartquestionplan',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_plan_records', to='businesses.assessment'),
        ),
    ]
