# Generated by Django 6.0.8 on 2026-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_smartquestioninstance_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartquestioninstance',
            name='expected_discovery_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smartquestioninstance',
            name='status',
            field=models.CharField(blank=True, default='UNANSWERED', max_length=30),
        ),
        migrations.AddField(
            model_name='smartquestioninstance',
            name='target_variable_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='smartquestionplan',
            name='business_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smartquestionplan',
            name='information_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smartquestionplan',
            name='reasoning_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smartquestionplan',
            name='regulatory_search_intent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='smartquestioninstance',
            name='variable_key',
            field=models.CharField(db_index=True, help_text='Canonical variable key in the profile registry.', max_length=100),
        ),
    ]
