# Generated by Django 6.0.8 on 2026-09-07 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('evidence', '0002_alter_source_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='firecrawl', max_length=50)),
                ('status', models.CharField(db_index=True, default='PENDING', help_text='PENDING, RUNNING, COMPLETED, FAILED, PARTIAL, UNAVAILABLE', max_length=30)),
                ('queries', models.JSONField(default=list, help_text='Generated query strings')),
                ('candidate_urls', models.JSONField(default=list, help_text='List of candidate URL records')),
                ('scraped_urls', models.JSONField(default=list, help_text='List of scraped URL records')),
                ('candidate_count', models.IntegerField(default=0)),
                ('scraped_count', models.IntegerField(default=0)),
                ('official_source_count', models.IntegerField(default=0)),
                ('verified_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('authority', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(default='CENTRAL', max_length=50)),
                ('applicability_statement', models.TextField()),
                ('prerequisite', models.TextField(blank=True, default='')),
                ('document_requirements', models.JSONField(blank=True, default=list)),
                ('fee_info', models.CharField(blank=True, default='', max_length=200)),
                ('deadline_info', models.CharField(blank=True, default='', max_length=200)),
                ('validity_info', models.CharField(blank=True, default='', max_length=200)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('CONFLICTING', 'Conflicting')], db_index=True, default='UNVERIFIED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requirements', to='businesses.business')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_requirements', to='evidence.evidence')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_requirements', to='evidence.source')),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requirements', to='ingestion.discoveryrun')),
            ],
            options={
                'ordering': ['requirement_name'],
            },
        ),
        migrations.AddIndex(
            model_name='discoveryrun',
            index=models.Index(fields=['business', '-created_at'], name='ingestion_d_busines_fd2c87_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterequirement',
            index=models.Index(fields=['discovery_run', 'verification_status'], name='ingestion_c_discove_7e7534_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterequirement',
            index=models.Index(fields=['business', 'verification_status'], name='ingestion_c_busines_428b6b_idx'),
        ),
    ]
