# Generated by Django 6.0.8 on 2026-10-03 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_source_status'),
        ('ingestion', '0002_discoveryrun_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(max_length=64)),
                ('normalized_content', models.TextField()),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_documents', to='evidence.source')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'content_hash'), name='unique_captured_source_version')],
            },
        ),
    ]
