# Generated by Django 6.0.8 on 2026-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_retrieveddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryrun',
            name='provider',
            field=models.CharField(default='serpapi', max_length=50),
        ),
    ]
