# Generated by Django 6.0.8 on 2026-09-05 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesses_business',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Compliance manager'), ('VIEWER', 'Viewer')], default='MANAGER', max_length=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesses_membership',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='businesses', through='businesses.BusinessMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessProfileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.PositiveIntegerField()),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('change_note', models.CharField(blank=True, max_length=300)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_versions', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profile_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesses_profile_version',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessmembership',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='uniq_business_user'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', '-created_at'], name='businesses__owner_i_dfffbe_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofileversion',
            index=models.Index(fields=['business', 'version'], name='businesses__busines_071be3_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessprofileversion',
            constraint=models.UniqueConstraint(fields=('business', 'version'), name='uniq_business_profile_version'),
        ),
    ]
