# Generated by Django 6.0.8 on 2026-09-08 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicability', '0002_alter_decisionrun_evaluation_date'),
        ('businesses', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], db_index=True, default='IN_PROGRESS', max_length=30)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('decision_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='applicability.decisionrun')),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='ingestion.discoveryrun')),
                ('profile_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='businesses.businessprofileversion')),
                ('question_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='onboarding.smartquestionplan')),
            ],
            options={
                'db_table': 'businesses_assessment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='businesses__busines_72308e_idx'), models.Index(fields=['created_by', '-created_at'], name='businesses__created_c8dd71_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'assessment_number'), name='uniq_business_assessment_num')],
            },
        ),
    ]
