# Generated by Django 6.0.8 on 2026-09-08 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkspaceState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='businesses.assessment')),
                ('active_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='businesses.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesses_user_workspace_state',
                'ordering': ['-updated_at'],
            },
        ),
    ]
