# Generated by Django 6.0.8 on 2026-10-03 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_userworkspacestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
                ('generation_key', models.CharField(max_length=64)),
                ('provider_metadata', models.JSONField(default=dict)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidance', to='businesses.assessment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_guidance', to='businesses.business')),
                ('profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.businessprofileversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
